import { Poppins } from 'next/font/google'
import './globals.css'
import { UserProvider } from '../contexts/UserContext'
// import Footer from "@/app/account/components/Footer";
import Image from 'next/image'

const poppins = Poppins({
  weight: ['300', '400', '500'],
  subsets: ['latin'],
  display: 'swap',
  fallback: ['system-ui', 'arial'],
  preload: true,
  adjustFontFallback: true
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className={` ${poppins.className} antialiased`}>
        {/* Logo */}
        <div className='w-full items-center m-auto'></div>
        <UserProvider>
          <div className=''>{children}</div>
        </UserProvider>
        <div className='items-center'></div>
      </body>
    </html>
  )
}
