import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Footer from "@/app/account/components/Footer";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
      <div
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
              {/* Logo */}
      <div className="w-full items-center m-auto">
        <Image
          src="/logo.svg"
          alt="Swift Connect"
          width={180}
          height={48}
          priority
        />
      </div>
      <div className="">

        {children}
      </div>
      <div className="items-center">
        <Footer />
      </div>
      </div>
  );
}
