import { Poppins } from 'next/font/google'
import '../globals.css'
import Footer from './components/Footer'
import Image from 'next/image'

const poppins = Poppins({
  weight: ['300', '400', '500'],
  subsets: ['latin'],
  display: 'swap',
  fallback: ['system-ui', 'arial'],
  preload: true,
  adjustFontFallback: true
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <div className={`${poppins.className} antialiased min-h-screen flex flex-col bg-white`}>
      <div className='flex-1 flex flex-col items-center justify-center'>{children}</div>
    </div>
  )
}
